openapi: '3.0.2'
info:
  title: API for human & pets
  version: '1.0'
servers:
  - url: http://localhost:4000/
  
paths:
  
  # People
  /people:
    get:
      tags:
        - "People"
      summary: Get people
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/person'
    post:
      tags:
        - "People"
      summary: Create new person
      parameters:
        - $ref: '#/components/parameters/personId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/person'
      responses:
        '200':
          description: New created person data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'

  /people/{personId}:

    get:
      tags:
        - "People"
      summary: Get a person by ID
      parameters:
        - $ref: '#/components/parameters/personId'
      responses:
        '200':
          description: A person data that has same id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'

    put:
      tags:
        - "People"
      summary: Update a person data
      parameters:
        - $ref: '#/components/parameters/personId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/person'
      responses:
        '200':
          description: New updated person data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'

    delete:
      tags:
        - "People"
      summary: Delete person by id
      parameters:
        - $ref: '#/components/parameters/personId'
      responses:
        '200':
          description: Deleted person data. Data before deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'

  # Pets
  /pets:
    get:
      tags:
        - "Pets"
      summary: List of pets
      responses:
        '200':
          description: List of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
    post:
      tags:
        - "Pets"
      summary: Create new person
      parameters:
        - $ref: '#/components/parameters/petId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pet'
      responses:
        '200':
          description: New created pet data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'

  /pets/{petId}:

    get:
      tags:
        - "Pets"
      summary: Get a pet by ID
      parameters:
        - $ref: '#/components/parameters/petId'
      responses:
        '200':
          description: A pet data that has same id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'

    put:
      tags:
        - "Pets"
      summary: Update a pet data
      parameters:
        - $ref: '#/components/parameters/petId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pet'
      responses:
        '200':
          description: New updated pet data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'

    delete:
      tags:
        - "Pets"
      summary: Delete pet by id
      parameters:
        - $ref: '#/components/parameters/petId'
      responses:
        '200':
          description: Deleted pet data. Data before deleted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'



tags:
  - name: Pets
  - name: People

components:
  schemas:
    person:
      type: object
      properties:
        id:
          type: string

    pet:
      type: object
      properties:
        id:
          type: string
        
  parameters:
    personId:
      name: personId
      in: path
      required: true
      schema:
        type: string
        example: sjdf68ASej09w#JH83o
      description: Person ID to look
    petId:
      name: petId
      in: path
      required: true
      schema:
        type: string
      description: Pet unique ID
